# Generated by Django 5.2.11 on 2026-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0002_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
